services:
  ei-video-obj-detection-runner:
    image: ${DOCKER_REGISTRY_BASE:-ghcr.io/arduino/}app-bricks/ei-models-runner:0.6.0
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"     
    ports:
      - ${BIND_ADDRESS:-0.0.0.0}:4912:4912
    volumes:
      - "${CUSTOM_MODEL_PATH:-/home/arduino/.arduino-bricks/ei-models/}:${CUSTOM_MODEL_PATH:-/home/arduino/.arduino-bricks/ei-models/}"
      - "/run/udev:/run/udev"
    command: ["--model-file", "${EI_OBJ_DETECTION_MODEL:-/models/ootb/ei/yolo-x-nano.eim}", "--dont-print-predictions", "--mode", "streaming", "--preview-original-resolution", "--camera", "${VIDEO_DEVICE:-/dev/video1}"]
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://ei-video-obj-detection-runner:4912 || exit 1" ]
      interval: 2s
      timeout: 2s
      retries: 25
