services:
  llamacpp-models-runner:
    image: ${DOCKER_REGISTRY_BASE:-ghcr.io/arduino/}app-bricks/llamacpp-npu-runner:0.11.0
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    environment:
      - LLAMA_LOG_LEVEL=error
      - LLAMA_ARG_HOST=0.0.0.0
      - LLAMA_ARG_PORT=9999
      - LLAMA_ARG_POLL=1000
      - LLAMA_ARG_BATCH=1024
      - LLAMA_ARG_UBATCH=256
      - LLAMA_ARG_MODELS_DIR=/models
      - LLAMA_ARG_FLASH_ATTN=${X_LLAMA_ARG_FLASH_ATTN:-on}
      - LLAMA_ARG_MODELS_MAX=${X_LLAMA_ARG_MODELS_MAX:-2}
      - LLAMA_ARG_CTX_SIZE=${X_LLAMA_ARG_CTX_SIZE:-16382}
      - LLAMA_ARG_REASONING=${X_LLAMA_ARG_REASONING:-off}
      - LLAMA_ARG_THREADS=${X_LLAMA_ARG_THREADS:-4}
      - LLAMA_ARG_CPU_MASK=${X_LLAMA_ARG_CPU_MASK:-0x0f}
      - GGML_HEXAGON_OPBATCH=2048
      - XDG_CACHE_HOME=/models
    working_dir: /models
    ports:
      - ${BIND_ADDRESS:-127.0.0.1}:9999:9999
      - ${BIND_ADDRESS_IPV6:-[::1]}:9999:9999
    mem_limit: 10g
    memswap_limit: 10g
    shm_size: 2g
    devices:
      - /dev/dma_heap/system
      - /dev/dma_heap/qcom,system
      - /dev/fastrpc-cdsp
      - /dev/fastrpc-cdsp-secure
    volumes:
      # Mount hexagon firmware
      - /usr/share/qcom/qcs8300/Qualcomm/QCS8300-RIDE/dsp/cdsp:/lib/dsp/cdsp
      - /var/lib/arduino-app-cli/models/llamacpp/:/models/
    # Pin on cores 0-3 for performance reasons: it's like using --cpu-mask 0x0f on llama-cli/server. Then set LLAMA_ARG_THREADS to 4 to use all those cores.
    cpuset: "0-3"