id: arduino:multimodal_llm
name: Multimodal Language Model
description: "Multimodal Language Model Brick lets your Arduino projects chat with a locally hosted AI model using text, images and audio."
requires_services: ["arduino:llamacpp"]
model: llamacpp:gemma-4-E2B-it-Q4_0
supported_boards: ["ventunoq"]
ai_frameworks_compatibility:
  - llamacpp
variables:
- name: LLAMA_ARG_CTX_SIZE
  description: Context size
  default_value: 16384
