id: arduino:vlm
name: Vision Language Model (VLM)
description: "Vision Language Model (VLM) Brick enables seamless integration with locally hosted VLMs for advanced AI capabilities in your Arduino projects."
requires_services:
  - id: arduino:genie
    when:
      model: "genie:*"
  - id: arduino:llamacpp
    when:
      model: "llamacpp:*"
model_by_boards:
    - platform: ventunoq
      model: genie:qwen3_vl_4b_instruct
    - platform: unoq
      model: llamacpp:SmolVLM2-500M-Video-Instruct-Q8_0
supported_boards: ["unoq", "ventunoq"]
ai_frameworks_compatibility:
  - genie
  - llamacpp
