# SPDX-FileCopyrightText: Copyright (C) Arduino s.r.l. and/or its affiliated companies
#
# SPDX-License-Identifier: MPL-2.0

from langchain_core.language_models import BaseChatModel, LanguageModelInput
from langchain_core.messages import AIMessage
from langchain_core.runnables import Runnable

from arduino.app_bricks.cloud_llm import ReasoningEffort
from arduino.app_bricks.cloud_llm.cloud_llm import ToolLike
from arduino.app_bricks.cloud_llm.memory import MessagePersistence
from arduino.app_bricks.llm import LargeLanguageModel
from arduino.app_utils import Logger, brick
from arduino.app_internal.core import get_brick_config, get_brick_configured_model

import openai
from typing import Any, Self
from collections.abc import Iterator, Sequence

logger = Logger("VisionLanguageModel")


@brick
class VisionLanguageModel(LargeLanguageModel):
    """A Brick for interacting with locally-based Vision Language Models (VLMs).

    It provides a simplified, unified interface for chatting with models like Qwenm, LLama,
    Gemma. It supports both synchronous 'one-shot' responses and streaming output,
    with optional conversational memory.
    """

    def __init__(
        self,
        system_prompt: str = "",
        temperature: float | None = 0.7,
        max_tokens: int = 512,
        timeout: int | None = None,
        tools: Sequence[ToolLike] | None = None,
        model: str | None = None,
        **kwargs: Any,
    ) -> None:
        """Initializes the VisionLanguageModel brick with the specified provider and configuration.

        Args:
            model (str | None): The specific model name or identifier to use (e.g., "genie:qwen3-4b").
                If not provided, model will be determined from app configuration or default brick configuration.
            system_prompt (str): A system-level instruction that defines the AI's persona
                and constraints (e.g., "You are a helpful assistant"). Defaults to empty.
            temperature (Optional[float]): The sampling temperature between 0.0 and 1.0.
                Higher values make output more random/creative; lower values make it more
                deterministic. Defaults to 0.7.
            max_tokens (int): The maximum number of tokens to generate in the response.
                Defaults to 256.
            timeout (Optional[int]): The maximum duration in seconds to wait for a response before
                timing out. Defaults to None.
            tools (Sequence[ToolLike] | None): BaseTool objects (from @tool or MCPClient.get_tools()) or plain
                callables (auto-wrapped into tools). Defaults to None.
            **kwargs: Additional arguments passed to the model constructor
        """

        if model is None:
            brick_config = get_brick_config(self.__class__)
            # app.yaml override first, then the brick default (model_by_boards or model)
            model = get_brick_configured_model(brick_config.get("id") if brick_config else None, brick_config=brick_config)
            logger.debug(f"Using model: '{model}'.")

        super().__init__(
            model=model,
            system_prompt=system_prompt,
            temperature=temperature,
            max_tokens=max_tokens,
            timeout=timeout,
            tools=tools,
            **kwargs,
        )
        super().with_memory(0)  # Initialize without memory enabled (0 means no history)

    def get_client(self) -> BaseChatModel | Runnable[LanguageModelInput, AIMessage]:
        """Returns the underlying LangChain model instance.

        This allows for advanced users to access the full capabilities of the model
        directly, such as calling `generate()` or `stream()` with custom message formats.

        Returns:
            BaseChatModel | Runnable[LanguageModelInput, AIMessage]: The LangChain chat model
                used internally, or the `Runnable` binding it to the registered tools.
        """
        return self._model

    def chat(
        self,
        message: str,
        images: Sequence[str | bytes] | None = None,
        reasoning_effort: ReasoningEffort | str | int | None = None,
    ) -> str:
        """Sends a message to the AI and blocks until the complete response is received.

        This method automatically manages conversation history if memory is enabled.

        Args:
            message (str): The input text prompt from the user.
            images (Sequence[str | bytes] | None): Optional sequence of image file paths or raw bytes to include in the prompt.
                None (default) sends a text-only message.
            reasoning_effort (ReasoningEffort | str | int | None): Optional effort level or token budget,
                as in `CloudLLM.chat`. None (default) keeps the default behavior; support depends on the local runner.

        Returns:
            str: The complete text response generated by the AI.

        Raises:
            RuntimeError: If the internal chain is not initialized or if the API request fails.
            ValueError: If `reasoning_effort` is not a supported level or budget.
            TypeError: If `reasoning_effort` is not a ReasoningEffort, str, int, or None.
        """
        try:
            return super()._chat_invoke(message=message, images=images, reasoning_effort=reasoning_effort)
        except (openai.BadRequestError, openai.APIError) as e:
            self._handle_api_error(logger, e)

    def chat_stream(self, message: str, images: Sequence[str | bytes] | None = None) -> Iterator[str]:
        """Sends a message to the AI and yields response tokens as they are generated.

        This allows for processing or displaying the response in real-time (streaming).
        The generation can be interrupted by calling `stop_stream()`.

        Args:
            message (str): The input text prompt from the user.
            images (Sequence[str | bytes] | None): Optional sequence of image file paths or raw bytes to include in the prompt.
                None (default) sends a text-only message.

        Yields:
            str: Chunks of text (tokens) from the AI response.

        Raises:
            RuntimeError: If the internal chain is not initialized or if the API request fails.
            AlreadyGenerating: If a streaming session is already active.
        """
        try:
            return super()._chat_stream_invoke(message=message, images=images)
        except (openai.BadRequestError, openai.APIError) as e:
            self._handle_api_error(logger, e)

    def stop_stream(self) -> None:
        """Signals the active streaming generation to stop.

        This sets an internal flag that causes the `chat_stream` iterator to break
        early. It has no effect if no stream is currently running.
        """
        super().stop_stream()

    def clear_memory(self) -> None:
        """Clears the conversational memory history.

        Resets the stored context. This is useful for starting a new conversation
        topic without previous context interfering. Only applies if memory is enabled.
        """
        super().clear_memory()

    def with_memory(
        self,
        max_messages: int = 0,
        persistence: bool | MessagePersistence | None = None,
    ) -> Self:
        """Enables conversational memory for this instance.

        Configures the Brick to retain a window of previous messages, allowing the
        AI to maintain context across multiple interactions. An optional persistence
        backend stores the history so it can resume across restarts.

        Args:
            max_messages (int): The maximum number of messages.
            persistence (bool | MessagePersistence | None): Optional persistence backend.
                `None` or `False` keep history in memory only (default behavior).
                `True` instantiates the default SQL-backed store. Pass a
                `MessagePersistence` implementation directly for full control.

        Returns:
            Self: The current instance, allowing for method chaining.
        """
        return super().with_memory(max_messages=max_messages, persistence=persistence)
